name = "pmo-hq"
main = "src/index.ts"
compatibility_date = "2024-06-15"
ai = true

# D1 Database for task staging and management
[[d1_databases]]
binding = "DB"
database_name = "pmo-hq-dev"
database_id = "YOUR_D1_DATABASE_ID"

# R2 Bucket for documentation
[[r2_buckets]]
binding = "DOCS_BUCKET"
bucket_name = "docs-bucket"

# Environment variables
[vars]
ENVIRONMENT = "development"


# Production environment
[env.production]
name = "pmo-hq"

[[env.production.d1_databases]]
binding = "DB"
database_name = "pmo-hq"
database_id = "YOUR_PRODUCTION_DB_ID"

[env.production.ai_gateway]
url = "${AI_GATEWAY_URL_PROD}"

[env.production.vars]
ENVIRONMENT = "production"

# Staging environment
[env.staging]
name = "pmo-hq-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "pmo-hq-staging"
database_id = "YOUR_STAGING_DB_ID"

[env.staging.ai_gateway]
url = "${AI_GATEWAY_URL_STAGING}"

# Cron triggers for periodic tasks
[triggers]
crons = [
  "0 */6 * * *",  # Every 6 hours (existing)
  "0 * * * *"     # Every hour (new)
]

# Build configuration
[build]
command = "pnpm run build"
watch_dir = "src"

# Development configuration
[dev]
port = 8787

[ai_gateway]
url = "${AI_GATEWAY_URL}"
