name = "pmo-hq"
main = "src/index.ts"
compatibility_date = "2024-06-15"
ai = true

[ai]
binding = "AI"

# D1 Database for task staging and management
[[d1_databases]]
binding = "DB"
database_name = "pmo-hq-v1"
database_id = "fd22a6b8-413c-4799-9965-20510bc21b2c"

# R2 Bucket for documentation
[[r2_buckets]]
binding = "DOCS_BUCKET"
bucket_name = "docs-content"

# Environment variables
[vars]
ENVIRONMENT = "development"


# Production environment
[env.production]
name = "pmo-hq"

[[env.production.d1_databases]]
binding = "DB"
database_name = "pmo-hq"
database_id = "YOUR_PRODUCTION_DB_ID"

[env.production.ai_gateway]
url = "${AI_GATEWAY_URL_PROD}"

[env.production.vars]
ENVIRONMENT = "production"

# Staging environment
[env.staging]
name = "pmo-hq-staging"

[env.staging.vars]
ENVIRONMENT = "staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "pmo-hq-v1-staging"
database_id = "a0c2ab15-294b-4285-9363-db09829f6440"

[env.staging.ai_gateway]
url = "${AI_GATEWAY_URL_STAGING}"

# Cron triggers for periodic tasks
[triggers]
crons = [
  "0 */6 * * *",  # Every 6 hours (existing)
  "0 * * * *"     # Every hour (new)
]

# Build configuration
[build]
command = "pnpm run build"
watch_dir = "src"

# Development configuration
[dev]
port = 8787

[ai_gateway]
url = "${AI_GATEWAY_URL}"
