
name = "clickup-orchestrator"
main = "src/orchestrate.ts"
compatibility_date = "2024-06-21"

[[queues.consumers]]
queue = "clickup-tasks"
max_batch_size = 10

[[durable_objects.bindings]]
name = "ORCHESTRATOR"
class_name = "OrchestrateDO"

[triggers]
crons = ["0 * * * *"] # hourly
