name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker

    steps:
      - uses: actions/checkout@v4
        with:
          path: .  # Ensures files go directly into /home/runner/work/pmo/pmo

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: "Debug: Show Current Directory & Lockfile"
        run: |
          pwd
          ls -lah

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Run Migrations
        run: pnpm run migrate:all
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to Cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "3.55.0" # optional pin
          command: wrangler deploy --env production
          secrets: |
            WEBHOOK_TOKEN
        env:
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}

      - name: Print Deployment URL
        run: echo "🚀 Deployed to ${{ steps.deploy.outputs.deployment-url }}"
