name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: 🔍 Debug Info
        run: |
          echo "--- 📂 Current Directory ---"
          pwd
          echo "--- 📄 Files in Root ---"
          ls -lah
          echo "--- 📄 Contents of pnpm-lock.yaml ---"
          cat pnpm-lock.yaml || echo "⚠️ pnpm-lock.yaml not found"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Project
        run: pnpm run build

      - name: Run Migrations
        run: pnpm run migrate:all
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Deploy to Cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "3.55.0"
          command: deploy --env production
          secrets: |
            WEBHOOK_TOKEN
        env:
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}

      - name: Print Deployment URL
        run: echo "🚀 Deployed to ${{ steps.deploy.outputs.deployment-url }}"
